import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ImLinkedin } from "react-icons/im";
import { SiGmail } from "react-icons/si";
import { FaGithub } from "react-icons/fa";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.aboutMeContainer}> */}
          <h1 className={styles.title}>
            <span className={styles.wave}>👋</span> I&apos;m Ben
          </h1>
          <p className={styles.aboutMe}>
          I am a Chattanooga-based web developer with a passion for creating things. I take great personal pride in building beautiful, functional, and high-performing web applications. I work with React, Node, Express, Postgres and other technologies built with Javascript and Ruby.
          </p>
        {/* </div> */}
        {/* <div className={styles.photoContainer}>
          <Image     
            alt='Ben Aplin photo'
            src='/headshot.jpg'
            width='250'
            height='250'
            />
        </div> */}
      </main>
      <footer className={styles.footer}>
        <a href='https://www.linkedin.com/in/benjaminaplin/'>
          <ImLinkedin size='64'/>
        </a>
        <a href='https://github.com/benjaminaplin'>
          <FaGithub size='64'/>
        </a>
      </footer>
    </div>
  )
}
