import styles from '../styles/Home.module.css'
import { Footer } from './UI/footer';
import Head from 'next/head'
import { Header } from './UI/header';

export default function Home() {
  return (  
    <div className={styles.container}>
      <Head>
        <title>Ben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={styles.wave}>👋</span> I&apos;m Ben, a Web Developer 
        </h1>
        <p className={styles.aboutMe}>
        I am a Chattanooga-based software engineer with a passion for creating things. I take great personal pride in building beautiful, functional, and high-performing web applications. I primarily work with React, Node, Express, Postgres and other technologies built with Javascript and Ruby.
        </p>
      </main>
      <Footer />
    </div>  
  )
}
